// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ipqabejpjrynrjbiwrqy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlwcWFiZWpwanJ5bnJqYml3cnF5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAyNDg2ODQsImV4cCI6MjA2NTgyNDY4NH0.49h2LTtR9h4Q62OTqURRTC-chxjQ4hS0N5nSdqLhW38";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);